name: Monitor and Update Alephium Mainnet Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 2: Fetch Latest Alephium Version
      - name: Fetch Latest Alephium Version
        id: fetch_version
        shell: bash
        run: |
          LATEST_VERSION=$(curl -s https://hub.docker.com/v2/repositories/alephium/alephium/tags/?page_size=1 | jq -r '.results[0].name')
          echo "Fetched version: $LATEST_VERSION"
          if [[ -z "$LATEST_VERSION" ]]; then
            echo "Error: Could not fetch a valid version from Docker Hub"
            exit 1
          fi
          echo "::set-output name=version::$LATEST_VERSION"

      # Step 3: Upload Snapshot file manually (use latest version v3)
      - name: Upload Snapshot File
        uses: actions/upload-artifact@v3
        with:
          name: snapshot-file
          path: /Users/scarnes/Downloads/full-node-data--without-indexes-2024-12-14.tar

      # Step 4: Download the Snapshot Artifact
      - name: Download Snapshot File
        uses: actions/download-artifact@v3
        with:
          name: snapshot-file

      # Step 5: Build Docker Image with Snapshot
      - name: Build Docker Image with Snapshot
        run: |
          # Extract the snapshot file name
          SNAPSHOT_FILE="./full-node-data--without-indexes-2024-12-14.tar"
          
          # Build Docker image with the snapshot
          docker build --build-arg SNAPSHOT_PATH=$SNAPSHOT_FILE -t dohmoney/mainnet .

      # Step 6: Push the newly tagged image to your Docker Hub repository
      - name: Push Docker Image to Docker Hub
        run: |
          docker tag dohmoney/mainnet:latest dohmoney/mainnet:${{ steps.fetch_version.outputs.version }}
          docker tag dohmoney/mainnet:latest dohmoney/mainnet:$(date +%Y%m%d%H%M)
          docker push dohmoney/mainnet:latest
          docker push dohmoney/mainnet:${{ steps.fetch_version.outputs.version }}
          docker push dohmoney/mainnet:$(date +%Y%m%d%H%M)

      # Step 7: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
