name: Pull and Push Prebuilt Docker Image Using Docker Compose

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight to check for updates

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Alephium Stack repository
      - name: Checkout Alephium Stack
        uses: actions/checkout@v2
        with:
          repository: alephium/alephium-stack
          path: alephium-stack

      # Install Docker Compose using official method
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Log in to Docker Hub using credentials stored in secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Dynamically edit the docker-compose.yml file to update the image field
      - name: Modify Docker Compose File to Use Your Docker Hub Repo
        run: |
          cd alephium-stack/mainnet
          # Replace the default Alephium image with your Docker Hub repo and tag
          sed -i 's#alephium/alephium:v3.6.3#cyxeio/alphnode_test:latest#g' docker-compose.yml

      # Pull the latest image (if it has changed) and push to Docker Hub
      - name: Pull and Push Image
        run: |
          cd alephium-stack/mainnet
          docker-compose pull
          docker-compose push

      # Clean up unused Docker images to free space
      - name: Cleanup Docker Images
        run: docker image prune -f
