name: Monitor and Update Alephium Mainnet Docker Images

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: self-hosted  # Use the self-hosted runner

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 2: Fetch the latest Alephium Docker image version
      - name: Fetch Latest Alephium Version
        id: fetch_version
        shell: bash
        run: |
          # Fetch latest version from Docker Hub
          LATEST_VERSION=$(curl -s https://hub.docker.com/v2/repositories/alephium/alephium/tags/?page_size=1 | jq -r '.results[0].name')
          echo "Fetched version: $LATEST_VERSION"
          
          if [[ -z "$LATEST_VERSION" ]]; then
            echo "Error: Could not fetch a valid version from Docker Hub"
            exit 1
          fi
          
          echo "::set-output name=version::$LATEST_VERSION"
          
      # Step 3: Create the custom Dockerfile with snapshot loading
      - name: Create Custom Dockerfile with Snapshot Loading
        run: |
          cat <<EOF > Dockerfile
          FROM alephium/alephium:${{ steps.fetch_version.outputs.version }}
          ENV ALEPHIUM_HOME=/alephium-home/.alephium
          ENV ALEPHIUM_NETWORK=mainnet
          ENV SNAPSHOT_URL="https://alephium-archives.org/archives/mainnet/full-node-data/full-node-data-mainnet-with-indexes-2024-10-09.tar"
          ENV SNAPSHOT_FILE="/tmp/snapshot.tar"
          
          # Switch to root to install necessary packages
          USER root
          
          # Fix permissions issue, install curl, download snapshot fully, and extract
          RUN mkdir -p /var/lib/apt/lists/partial && \
              apt-get update && apt-get install -y curl && \
              echo "Downloading Alephium snapshot to \$SNAPSHOT_FILE" && \
              curl -L -C - "\$SNAPSHOT_URL" -o "\$SNAPSHOT_FILE" && \
              echo "Snapshot downloaded, now extracting..." && \
              tar --strip-components=1 -xv -f "\$SNAPSHOT_FILE" -C \$ALEPHIUM_HOME && \
              rm "\$SNAPSHOT_FILE" && \
              apt-get clean
          
          # Switch back to non-root user
          USER alephium
          
          ENTRYPOINT ["/bin/bash", "-c", "/alephium/bin/alephium-entrypoint.sh"]
          EOF

      # Step 4: Build the Docker image with a timeout of 8 hours
      - name: Build Docker Image with Snapshot
        timeout-minutes: 480  # Set the timeout to 8 hours
        run: |
          docker build -t dohmoney/mainnet:latest .

      # Step 5: Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag dohmoney/mainnet:latest dohmoney/mainnet:${{ steps.fetch_version.outputs.version }}
          docker tag dohmoney/mainnet:latest dohmoney/mainnet:$(date +%Y%m%d%H%M)

      # Step 6: Verify the tags created locally before pushing
      - name: List Docker Images and Tags
        run: docker images

      # Step 7: Push the newly tagged image to your Docker Hub repository
      - name: Push Docker Image to Docker Hub
        run: |
          docker push dohmoney/mainnet:latest
          docker push dohmoney/mainnet:${{ steps.fetch_version.outputs.version }}
          docker push dohmoney/mainnet:$(date +%Y%m%d%H%M)

      # Step 8: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
