name: Monitor and Update cyxeio/mainnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch the latest version from Docker Hub for `cyxeio/alphnode_test`
      - name: Get latest version from Docker Hub
        id: my_repo_version  # ID to reference in later steps
        run: |
          latest_tag=$(curl -s https://registry.hub.docker.com/v1/repositories/cyxeio/mainnet/tags | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest version in cyxeio/mainnet is $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 3: Pull the pre-built Docker image from `cyxeio/alphnode_test`
      - name: Pull your Docker Image
        run: |
          docker pull cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }}

      # Step 4: Tag the Docker image with the new version and push it
      - name: Tag Docker Image
        run: |
          docker tag cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }} cyxeio/mainnet:latest
          docker tag cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }} cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }}
          docker tag cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }} cyxeio/mainnet:$(date +%Y%m%d%H%M)

      # Step 5: Verify the tags created locally before pushing
      - name: List Docker Images and Tags
        run: |
          docker images  # List all images and tags

      # Step 6: Push the newly tagged image to your Docker Hub repository
      - name: Push Docker Image to Docker Hub
        run: |
          docker push cyxeio/mainnet:latest
          docker push cyxeio/mainnet:${{ steps.my_repo_version.outputs.tag }}  # Push the versioned tag
          docker push cyxeio/mainnet:$(date +%Y%m%d%H%M)

      # Step 7: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
