name: Build and Push Docker Image Using Docker Compose

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight to check for updates

jobs:
  update-docker-image:
    runs-on: ubuntu-latest

    steps:
      # Checkout the Alephium Stack repository
      - name: Checkout Alephium Stack
        uses: actions/checkout@v2
        with:
          repository: alephium/alephium-stack
          path: alephium-stack

      # Set up Docker Buildx (required for Docker Compose)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose using the official method
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Create Dockerfile dynamically in alephium-stack/mainnet
      - name: Create Dockerfile
        run: |
          cd alephium-stack/mainnet
          cat <<EOF > Dockerfile
          # Use the Alephium base image
          FROM alephium/alephium:v3.6.3
          
          # Set working directory inside the container
          WORKDIR /app

          # Copy all files from current directory into the container (optional, if you have app code)
          COPY . .

          # Expose the necessary port(s)
          EXPOSE 9973

          # Command to run when the container starts (modify as necessary)
          CMD ["./start.sh"]
          EOF

      # Modify the docker-compose.yml file to ensure it uses your Docker Hub repo
      - name: Modify Docker Compose File to Use Your Docker Hub Repo
        run: |
          cd alephium-stack/mainnet
          sed -i 's#alephium/alephium:v3.6.3#cyxeio/alphnode_test:latest#g' docker-compose.yml

      # Build and push the image using Docker Compose
      - name: Build and Push Docker Image
        run: |
          cd alephium-stack/mainnet
          docker-compose build
          docker-compose push

      # Clean up unused Docker images to free space
      - name: Cleanup Docker Images
        run: docker image prune -f
