name: Monitor and Update Alephium Mainnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  update-mainnet:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the Alephium Stack repository
      - name: Checkout Alephium Stack
        uses: actions/checkout@v2
        with:
          repository: alephium/alephium-stack
          path: alephium-stack

      # Step 2: Install Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 3: Use the Makefile to start the mainnet
      - name: Start Mainnet
        run: |
          cd alephium-stack
          make start-mainnet

      # Step 4: Build the Docker image for mainnet
      - name: Build Docker Image
        run: |
          cd alephium-stack/mainnet
          docker-compose build --no-cache
          docker tag cyxeio/alphnode_test:latest cyxeio/alphnode_test:$(date +%Y%m%d%H%M)
          docker push cyxeio/alphnode_test:$(date +%Y%m%d%H%M)
          docker push cyxeio/alphnode_test:latest

      # Step 5: Stop the mainnet after building
      - name: Stop Mainnet
        run: |
          cd alephium-stack
          make stop-mainnet

      # Step 6: Clean up unused Docker images
      - name: Cleanup Docker Images
        run: docker image prune -f
