name: Monitor and Update Alephium Mainnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 2: Pull the pre-built Docker image from Alephium
      - name: Pull Alephium Docker Image
        run: |
          docker pull alephium/alephium:v3.6.3  # Pull the Alephium image

      # Step 3: Tag the Docker image for your Docker Hub repo
      - name: Tag Docker Image
        run: |
          docker tag alephium/alephium:v3.6.3 cyxeio/alphnode_test:latest
          docker tag alephium/alephium:v3.6.3 cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 4: Push the newly tagged image to your Docker Hub repository
      - name: Push Docker Image to Docker Hub
        run: |
          docker push cyxeio/alphnode_test:latest
          docker push cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 5: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
