name: Monitor and Update Alephium Mainnet

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch the latest Alephium image tag from Docker Hub
      - name: Get latest Alephium version
        id: alephium_version  # Set an ID so we can reference the output in later steps
        run: |
          latest_tag=$(curl -s https://registry.hub.docker.com/v1/repositories/alephium/alephium/tags | jq -r '.[].name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "Latest Alephium version is $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 3: Pull the latest Alephium Docker image
      - name: Pull Alephium Docker Image
        run: |
          docker pull alephium/alephium:${{ steps.alephium_version.outputs.tag }}  # Pull the latest version dynamically

      # Step 4: Tag the Docker image for your Docker Hub repo
      - name: Tag Docker Image
        run: |
          docker tag alephium/alephium:${{ steps.alephium_version.outputs.tag }} cyxeio/alphnode_test:latest
          docker tag alephium/alephium:${{ steps.alephium_version.outputs.tag }} cyxeio/alphnode_test:${{ steps.alephium_version.outputs.tag }}
          docker tag alephium/alephium:${{ steps.alephium_version.outputs.tag }} cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 5: Verify the tags created locally before pushing
      - name: List Docker Images and Tags
        run: |
          docker images  # List all images and tags

      # Step 6: Push the newly tagged image to your Docker Hub repository
      - name: Push Docker Image to Docker Hub
        run: |
          docker push cyxeio/alphnode_test:latest
          docker push cyxeio/alphnode_test:${{ steps.alephium_version.outputs.tag }}  # Push the versioned tag
          docker push cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 7: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
