name: Monitor and Update cyxeio/mainnet and cyxeio/alphnode_test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  pull-tag-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch the latest version from Alephium GitHub (Mainnet)
      - name: Get latest version from Alephium GitHub (Mainnet)
        id: alephium_mainnet_version  # ID to reference in later steps
        run: |
          latest_commit=$(curl -s https://api.github.com/repos/alephium/alephium-stack/commits/mainnet | jq -r '.[0].commit.message')
          version=$(echo "$latest_commit" | grep -oE 'Full node [0-9]+\.[0-9]+\.[0-9]+' | awk '{print $3}')
          echo "Latest version in Alephium Mainnet: $version"
          echo "::set-output name=alephium_mainnet_tag::$version"

      # Step 2: Fetch the latest version from Alephium GitHub (Testnet)
      - name: Get latest version from Alephium GitHub (Testnet)
        id: alephium_testnet_version  # ID to reference in later steps
        run: |
          latest_commit=$(curl -s https://api.github.com/repos/alephium/alephium-stack/commits/testnet | jq -r '.[0].commit.message')
          version=$(echo "$latest_commit" | grep -oE 'Full node [0-9]+\.[0-9]+\.[0-9]+' | awk '{print $3}')
          echo "Latest version in Alephium Testnet: $version"
          echo "::set-output name=alephium_testnet_tag::$version"

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      # Step 4: Pull the Docker image from cyxeio/mainnet using the Alephium Mainnet version
      - name: Pull Docker Image for cyxeio/mainnet
        run: |
          if [ -z "${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }}" ]; then
            echo "No valid tag found for mainnet, exiting."
            exit 1
          else
            docker pull cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }}
          fi

      # Step 5: Pull the Docker image from cyxeio/alphnode_test using the Alephium Testnet version
      - name: Pull Docker Image for cyxeio/alphnode_test
        run: |
          if [ -z "${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }}" ]; then
            echo "No valid tag found for testnet, exiting."
            exit 1
          else
            docker pull cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }}
          fi

      # Step 6: Tag the Docker image for cyxeio/mainnet
      - name: Tag Docker Image for cyxeio/mainnet
        run: |
          docker tag cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }} cyxeio/mainnet:latest
          docker tag cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }} cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }}
          docker tag cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }} cyxeio/mainnet:$(date +%Y%m%d%H%M)

      # Step 7: Tag the Docker image for cyxeio/alphnode_test
      - name: Tag Docker Image for cyxeio/alphnode_test
        run: |
          docker tag cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }} cyxeio/alphnode_test:latest
          docker tag cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }} cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }}
          docker tag cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }} cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 8: List Docker Images and Tags
      - name: List Docker Images and Tags
        run: |
          docker images  # List all images and tags

      # Step 9: Push Docker Image to Docker Hub for cyxeio/mainnet
      - name: Push Docker Image to Docker Hub (cyxeio/mainnet)
        run: |
          docker push cyxeio/mainnet:latest
          docker push cyxeio/mainnet:v${{ steps.alephium_mainnet_version.outputs.alephium_mainnet_tag }}
          docker push cyxeio/mainnet:$(date +%Y%m%d%H%M)

      # Step 10: Push Docker Image to Docker Hub for cyxeio/alphnode_test
      - name: Push Docker Image to Docker Hub (cyxeio/alphnode_test)
        run: |
          docker push cyxeio/alphnode_test:latest
          docker push cyxeio/alphnode_test:v${{ steps.alephium_testnet_version.outputs.alephium_testnet_tag }}
          docker push cyxeio/alphnode_test:$(date +%Y%m%d%H%M)

      # Step 11: Clean up unused Docker images to save space
      - name: Cleanup Docker Images
        run: docker image prune -f
